version: '3.8'
services:
  database:
    build: ./Database
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: ./Server
    ports: 
      - "8080:7000"
    depends_on:
      - database
  
volumes:
  db_data:
